Replace python depcheck with bash depcheck

diff --git a/depcheck b/depcheck
--- a/depcheck
+++ b/depcheck
@@ -1,114 +1,68 @@
-#!/usr/bin/python
+#!/bin/bash
 
-from optparse import OptionParser
-import logging
-import os
-from repoutils import repoclosure
-import tempfile
+if [[ "$1" == "-h" || "$1" == "--help" ]]; then
+    echo "Usage: checkdep repo_name [optional: custom yum.conf]"
+	echo "Example: checkdep centos7-rutgers-testing-temp"
+	exit 0
+fi
 
-MASHD="/etc/mash"
-TGTD="/mnt/koji/mash"
+if [[ $# -eq 2 && ! -f "$2" ]]; then
+    echo "That file does not exist"
+    exit 1
+fi
 
-def main(options, args):
-    if options.verbose:
-        logging.basicConfig(format="[%(levelname)s] %(message)s", 
-                           level=logging.DEUG)
-        logging.debug("Showing verbose output")
-    else:
-        logging.basicConfig(format="[%(levelname)s] %(message)s",
-                        level=logging.INFO) 
+input=$1
+ver=${input//[^0-9]/}
+error=false
 
-    repo = args[0]
+echo "Checking Dependencies"
 
-    if not options.directory and not repo_exists(repo):
-        logging.critical("Repo does not exist: {}".format(repo))
-    else:
-        if options.directory:
-            path = repo
-        else:
-            path = get_repo_path(repo)
-       
-        errors = depcheck_directory(path)
-        if errors:
-            logging.error("Dependency issues found:")
-            for e in errors:
-                logging.error(e)
-        else:
-            logging.info("No dependency issues found")
+if [[ $ver -lt 7 ]]; then
+    if [[ $# -eq 2 ]]; then
+        repoclosure -t -r $1 --config=/etc/repotools2-yum.conf --config=$2 \
+            -l base$ver-32 -l updates$ver-32 -l extras$ver-32 \
+            -l base$ver -l updates$ver -l extras$ver > /tmp/repolines.txt
+    else
+        repoclosure -t -r $1 --config=/etc/repotools2-yum.conf \
+            -l base$ver-32 -l updates$ver-32 -l extras$ver-32 \
+            -l base$ver -l updates$ver -l extras$ver > /tmp/repolines.txt
+    fi
+else
+    if [[ $# -eq 2 ]]; then
+        repoclosure -t -r $1 --config=/etc/repotools2-yum.conf --config=$2 \
+            -l base$ver -l updates$ver -l extras$ver > /tmp/repolines.txt
+    else
+        repoclosure -t -r $1 --config=/etc/repotools2-yum.conf \
+            -l base$ver -l updates$ver -l extras$ver > /tmp/repolines.txt
+    fi
+fi
 
+sed -n '/unresolved\ deps/{:a;n;/package:\ /b;p;ba}' /tmp/repolines.txt \
+    > /tmp/unresolved_deps.txt
 
-def repo_exists(repo):
-    """Returns true if a mash file for the repo exists"""
-    file = repo + ".mash"
-    return os.path.exists(os.path.join(MASHD, file))
+touch /tmp/real_dep_problems.txt
 
-def get_repo_path(repo):
-    """Returns the path of the given repo"""
-    return os.path.join(TGTD, repo)
+while read line; do
+    grep -q -i $line /etc/depcheck2.ignore
+    if [[ "$?" != "0" ]]; then
+        echo "Missing dependency: $line" > tee -a /tmp/real_dep_problems.txt
+        error=true
+    fi
+done < /tmp/unresolved_deps.txt
 
-def depcheck_directory(path):
-    """Returns a list of dependency error messages if the repo at the given 
-    directory is not clean"""
-    rc_config = generate_config(path)
-    rc = repoclosure.RepoClosure(config=rc_config)
-    os.remove(rc_config)
+if [ "$error" = true ]; then
+    echo -e "\nDependency errors detected:"
+    cat /tmp/real_dep_problems.txt
+    echo "\nOutput from repoclosure:"
+    cat /tmp/repolines.txt
+    echo -e ""
+    exit 1
+fi
 
-def generate_config(path):
-    """Returns the path to a temp file of the yum config for RepoClosure
-    for the given path. The file must be deleted once done with it"""
-    (file_desc, path) = tempfile.mkstemp()
-    contents = """[main]
-debuglevel=2
-logfile=/var/log/yum.log
-pkgpolicy=newest
-distroverpkg=centos-release
-reposdir=/dev/null
-cachedir=/var/tmp/yum
-keepcache=0
+rm /tmp/real_dep_problems.txt
+rm /tmp/repolines.txt
+rm /tmp/unresolved_deps.txt
 
-[base]
-name=CentOS - Base
-baseurl=file:///army/centos/centos/6/os/x86_64/
+echo "No Dependency errors found"
 
-[update]
-name=CentOS - Updates
-baseurl=file:///army/centos/centos/6/updates/x86_64/
-
-#[addons]
-#name=CentOS - Addons
-#baseurl=file:///army/centos/centos/6/addons/x86_64/
-
-[extras]
-name=CentOS - Extras
-baseurl=file:///army/centos/centos/6/extras/x86_64/
-
-[rutgers]
-name=CentOS rutgers Tree
-baseurl=file:///army/rpmprivate/centos/rutgers/rutgers/6/x86_64/
-"""
-    os.write(file_desc, contents)
-    os.close(file_desc)
-    return path
-
-if __name__ == "__main__":
-    parser = OptionParser(usage="usage: %prog [options] argument")
-    
-    parser.add_option("--nomail", default=True,
-                      action="store_false", dest="send_mail",
-                      help="do not send email notifications")
-    parser.add_option("-v", "--verbose", default=False,
-                      action="store_true", dest="verbose",
-                      help="show verbose output")
-    parser.add_option("-q", "--quiet", default=True,
-                      action="store_false", dest="show_output",
-                      help="don't show output (will show errors)")
-    parser.add_option("-d", "--directory", default=False,
-                      action="store_true", dest="directory",
-                      help="argument is a directory, not the name of a repo")
-
-    (options, args) = parser.parse_args()
-
-    if len(args) == 0:
-        print "Missing required argument"
-    else:
-        main(options, args)
+exit 0
