Fix bug and add multi-package support for pull

diff --git a/pullpackage b/pullpackage
--- a/pullpackage
+++ b/pullpackage
@@ -31,19 +31,35 @@ fi
 touch $LOCK
 
 echo "Untagging packages"
-koji untag-pkg $1 $2
-
-if [[ "$?" != "0" ]]; then
-	echo "Failed to untag packages!"
-    rm $LOCK
-	exit 1
-fi
+for var in "$@"
+do
+    # probably don't need an if to skip first arg, but too lazy to find another
+    # way lol
+    if [[ $var -ne $1 ]]; then
+        koji untag-pkg $1 $var
+        if [[ "$?" != "0" ]]; then
+	        echo "Failed to untag package $var!"
+            rm $LOCK
+	        exit 1
+        fi
+    fi
+done
 
 echo "Called rebuild-repo"
 rebuild-repo $1 -k -nolock
 if [[ "$?" != "0" ]]; then
 	echo "Rebuild-Repo failed!! Retagging package and exiting..."
-	koji tag-pkg $1 $2
+    for var in "$@"
+    do
+        # probably don't need an if to skip first arg, but too lazy to find another
+        # way lol
+        if [[ $var -ne $1 ]]; then
+            koji tag-pkg $1 $var
+            if [[ "$?" != "0" ]]; then
+	            echo "Failed to tag package $var!"
+            fi
+        fi
+    done
     echo "Sending Mail"
     echo -e "Pullpackage failed with the following output:\n\nDependency Errors detected:\n$(cat $RDPROB)\n\nOutput from repoclosure:\n$(cat $TMPRPL)" | \
         mailx -r "roji@koji.rutgers.edu" -s "CentOS Broken Dependencies" "$EMAIL"
@@ -54,8 +70,19 @@ if [[ "$?" != "0" ]]; then
 	exit 1
 fi
 
-echo -e "Pullpackage successfully pulled $2 from $1 along with its breakout packages" | \
-    mailx -r "roji@koji.rutgers.edu" -s "CentOS Pull Successful - $2" "$EMAIL"
+echo "Sending email(s)"
+for var in "$@"
+do
+    # probably don't need an if to skip first arg, but too lazy to find another
+    # way lol
+    if [[ $var -ne $1 ]]; then
+        echo -e "Pushpackage successfully pulled $var to $1 along with its breakout packages" | \
+            mailx -r "roji@koji.rutgers.edu" -s "CentOS Pull Successful - $var" "$EMAIL"
+        if [[ "$?" != "0" ]]; then
+	        echo "Failed to send email for package $var"
+        fi
+    fi
+done
 
 rm $RDPROB
 rm $TMPRPL
diff --git a/pushpackage b/pushpackage
--- a/pushpackage
+++ b/pushpackage
@@ -36,7 +36,7 @@ do
     # probably don't need an if to skip first arg, but too lazy to find another
     # way lol
     if [[ $var -ne $1 ]]; then
-        koji tag-pkg $1 $2
+        koji tag-pkg $1 $var
         if [[ "$?" != "0" ]]; then
 	        echo "Failed to tag package $var!"
             rm $LOCK
@@ -50,7 +50,17 @@ echo "Called rebuild-repo"
 rebuild-repo $1 -nolock -k
 if [[ "$?" != "0" ]]; then
 	echo "Rebuild-Repo failed!! Untagging packages and exiting..."
-	koji untag-pkg $1 $2
+    for var in "$@"
+    do
+        # probably don't need an if to skip first arg, but too lazy to find another
+        # way lol
+        if [[ $var -ne $1 ]]; then
+            koji untag-pkg $1 $var
+            if [[ "$?" != "0" ]]; then
+	            echo "Failed to untag package $var!"
+            fi
+        fi
+    done
     echo "Sending Mail"
     echo -e "Pushpackage failed with the following output:\n\nDependency Errors detected:\n$(cat $RDPROB)\n\nOutput from repoclosure:\n$(cat $TMPRPL)" | \
         mailx -r "roji@koji.rutgers.edu" -s "CentOS Broken Dependencies" "$EMAIL"
@@ -72,8 +82,8 @@ do
     # probably don't need an if to skip first arg, but too lazy to find another
     # way lol
     if [[ $var -ne $1 ]]; then
-        echo -e "Pushpackage successfully pushed $2 to $1 along with its breakout packages" | \
-            mailx -r "roji@koji.rutgers.edu" -s "CentOS Push Successful - $2" "$EMAIL"
+        echo -e "Pushpackage successfully pushed $var to $1 along with its breakout packages" | \
+            mailx -r "roji@koji.rutgers.edu" -s "CentOS Push Successful - $var" "$EMAIL"
         if [[ "$?" != "0" ]]; then
 	        echo "Failed to send email for package $var"
         fi
